### ISSUE TITLE
Consider mod enabled status when loading mods

### ISSUE THREAD

**Issue by jixxed** [jixxed/StationeersMods#1]

**Comment by kaedys** [comment]
Would like to :+1: this, just went through a mess of troubleshooting trying to figure out why the mod I'd disabled still seemed to be active.  Found the issue when I tried to unsubscribe to said mod to nuke it, and the DLL flagged as being open in Stationeers.  Would be nice if the mods were only loaded if actually enabled, as it's quite misleading otherwise.  If that's not something you feel makes sense to change, I would recommend at least highlighting in the Usage section of the README that mod DLL scripts are loaded even if the mod is "disabled" in-game.

**Comment by jixxed** [comment]
check added in 1.0.11.0

**Comment by kaedys** [comment]
Much appreciated!
